### ISSUE TITLE
New device connect() not working in 1.2.0, was working in 1.1.2

### ISSUE THREAD

**Issue by khirstinova** [aws/aws-iot-device-sdk-python#70] opened 2017-09-28 14:15 UTC
Hi,

In 1.1.2, we had this working.  When a new certificate made with the procedure described here: https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/
would connect, we had the lambda function that would execute and activate the certificate, described here:
https://github.com/awslabs/aws-iot-examples/blob/master/justInTimeRegistration/deviceActivation.js

In 1.1.2, what would happen was that we would get an initial disconnect, and the backOff timing would initiate and eventually the connection would be successful.  These are the logs from that interaction:

`2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for backoff timing: baseReconnectTime = 1 sec (Line:239)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for backoff timing: maximumReconnectTime = 32 sec (Line:240)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for backoff timing: minimumConnectTime = 20 sec (Line:241)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for publish queueing: queueSize = -1 (Line:248)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for publish queueing: dropBehavior = Drop Newest (Line:252)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Custom setting for draining interval: 0.5 sec (Line:262)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Set maximum connect/disconnect timeout to be 10 second. (Line:52)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Set maximum MQTT operation timeout to be 5 second (Line:59)
2017-09-27 14:59:12: (INFO:AWSIoTPythonSDK.core.protocol.mqttCore) Connection type: TLSv1.2 Mutual Authentication (Line:288)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Disconnect result code 1 (Line:123)
2017-09-27 14:59:12: (DEBUG:AWSIoTPythonSDK.core.util.progressiveBackoffCore) backOff: current backoff time is: 1 sec. (Line:61)
2017-09-27 14:59:13: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Disconnect result code 1 (Line:123)
2017-09-27 14:59:13: (DEBUG:AWSIoTPythonSDK.core.util.progressiveBackoffCore) backOff: current backoff time is: 2 sec. (Line:61)
2017-09-27 14:59:15: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Connect result code 0 (Line:117)
2017-09-27 14:59:15: (INFO:AWSIoTPythonSDK.core.protocol.mqttCore) Connected to AWS IoT. (Line:302)
2017-09-27 14:59:15: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Connect time consumption: 3290.0ms. (Line:303)
2017-09-27 14:59:15: (DEBUG:AWSIoTPythonSDK.core.protocol.mqttCore) Started a subscribe request 1 (Line:392)`

In 1.2.0, all we ever get is a connection timeout.  The lambda function DID execute on AWS and the certificate is activated, but the connect fails.  Here are the logs from that:

`2017-09-28 10:02:24,683 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queueing: max queue size: -1
2017-09-28 10:02:24,706 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring offline requests queue draining interval: 0.500000 sec
2017-09-28 10:02:24,739 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring connect/disconnect time out: 6.000000 sec
2017-09-28 10:02:24,760 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Configuring MQTT operation time out: 5.000000 sec
2017-09-28 10:02:24,823 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
rming async connect...       IoTPythonSDK.core.protocol.mqtt_core - INFO - Perfo--More-- (82% of 13923 bytes)
2017-09-28 10:02:24,872 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 30.000000 sec
2017-09-28 10:02:24,895 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2017-09-28 10:02:24,923 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2017-09-28 10:02:33,253 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2017-09-28 10:02:33,324 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
2017-09-28 10:02:33,329 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2017-09-28 10:02:33,343 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 1 sec.
2017-09-28 10:02:33,338 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2017-09-28 10:02:33,378 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Cleaning up before stopping event consuming
2017-09-28 10:02:33,384 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event queue cleared
2017-09-28 10:02:33,393 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Stopping network I/O thread...
2017-09-28 10:02:34,374 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Network thread stopped
2017-09-28 10:02:34,379 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event callbacks cleared
2017-09-28 10:02:34,393 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Event consuming thread stopped
2017-09-28 10:02:39,290 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Connect timed out
2017-09-28 10:02:39,345 - AWSIoTPythonSDK.core - INFO - Unexpected error: Traceback (most recent call last):
  File "/etc/scripts/configureAWSIoTSettings.py", line 184, in <module>
    main()
  File "/etc/scripts/configureAWSIoTSettings.py", line 176, in main
    configurator.connectAndSubscribe()
  File "/etc/scripts/configureAWSIoTSettings.py", line 58, in connectAndSubscribe
    self.AWSIotDeviceClient.connect()
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 408, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 171, in connect
    raise connectTimeoutException()
connectTimeoutException
`

It doesn't seem to matter what parameters I give to the initial configuration or what the timeouts are, it always times out in 1.2.0

**Comment by khirstinova** [comment] 2017-09-28 14:26
If we run the registration program again, then the connect() is successful, but this is because the connect() call is happening AFTER the cert is marked active.  We don't wish to have to script this to run two times in order to work.  When we are provisioning new devices in our production facility, we would like the registration to work the first time.

**Comment by hedeshianaws** [comment] 2017-10-03 04:35
Hello, thank you for reporting this issue. We've had a couple reports of this issue and we are working towards a resolution. I would like to confirm the delta in behavior you are seeing. It sounds like with 1.2.0 it is requiring manual re-connection whereas in 1.1.2, you were seeing the SDK eventually re-try and succeed. Is that correct?

**Comment by khirstinova** [comment] 2017-10-03 12:40
This is absolutely correct.  Seems like the backoff timing mechanism wasn't working.  But, as you said, the manual reconnect works.

**Comment by hedeshianaws** [comment] 2017-10-04 01:14
Alright, I was able to root cause the issue. There was a rather large change to the async client support which broke the auto-reconnect logic when the failure is encountered in certain states. We're still looking into a proper long-term fix and will include it in the next release. In the meantime, please try out the patch below and let me know if it works for you:

diff --git a/AWSIoTPythonSDK/core/protocol/internal/workers.py b/AWSIoTPythonSDK/core/protocol/internal/workers.py
index 656578a..20219a4 100644
--- a/AWSIoTPythonSDK/core/protocol/internal/workers.py
+++ b/AWSIoTPythonSDK/core/protocol/internal/workers.py
@@ -138,6 +138,12 @@ class EventConsumer(object):
 
     def _dispatch_one(self):
         mid, event_type, data = self._event_queue.get()
+
+        status = self._client_status.get_status()
+        if status == ClientStatus.CONNECT and event_type == EventTypes.DISCONNECT:
+            self._logger.debug("Ignored [disconnect] event while in CONNECTing state")
+            return
+
         if mid:
             self._dispatch_methods[event_type](mid, data)
             self._internal_async_client.invoke_event_callback(mid, data=data)

**Comment by khirstinova** [comment] 2017-10-04 17:42
Thanks!  That actually did work quite well.

**Comment by khirstinova** [comment] 2017-10-04 18:09
Relevant logs after change:

2017-10-04 12:34:03,038 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync connect...
2017-10-04 12:34:03,061 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async connect...
2017-10-04 12:34:03,077 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Keep-alive: 30.000000 sec
2017-10-04 12:34:03,095 - AWSIoTPythonSDK.core.protocol.mqtt_core - DEBUG - Passing in general notification callbacks to internal client...
2017-10-04 12:34:03,116 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Filling in fixed event callbacks: CONNACK, DISCONNECT, MESSAGE
2017-10-04 12:34:11,479 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Starting network I/O thread...
2017-10-04 12:34:11,552 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Ignored [disconnect] event while in CONNECTing state
2017-10-04 12:34:11,561 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
2017-10-04 12:34:11,575 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 1 sec.
2017-10-04 12:34:15,874 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
2017-10-04 12:34:15,888 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
2017-10-04 12:34:15,879 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - No need for recovery
2017-10-04 12:34:15,908 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
2017-10-04 12:34:15,971 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync subscribe...
2017-10-04 12:34:15,983 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Adding a new subscription record: device/new/0D4SPPH0O3UTPYO qos: 1
2017-10-04 12:34:16,019 - AWSIoTPythonSDK.core.protocol.internal.clients

**Comment by hedeshianaws** [comment] 2017-10-04 18:50
Awesome! Glad it worked out for you. Please let us know if you have any other questions.

**Comment by hedeshianaws** [comment] 2017-10-04 18:50
re-open (closed by mistake)

**Comment by hedeshianaws** [comment] 2017-10-24 18:02
@khirstinova I've had a chance to circulate that workaround with the author of the 1.2.0 change which introduced the change in behavior. First, I recommend not using that workaround as it breaks the state machine in ways which can manifest down the line. Second, it appears that behavior change is intentional. Since the SDK cannot tell the difference between a JIT connection failure and a regular certificate rejection, it will not attempt to reconnect if the initial connect failed. The argument is that the SDK should not keep blindly re-trying if there is a bad certificate. The Hence, you'll need to call connect() in a loop with a back-off timer if you know your device is using JIT.

**Closed by hedeshianaws** 2017-10-24 18:02 UTC
Labels: bug
