### ISSUE TITLE
ClientToken is limited to 64 bytes

### ISSUE THREAD

**Issue by rkawajiri** [aws/aws-iot-device-sdk-python#28] opened 2016-12-07 08:19 UTC
I cannot find documentations about the limits of client token (e.g.  http://docs.aws.amazon.com/iot/latest/developerguide/iot-limits.html, http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-document.html#client-token ). However, based on my try-and-error with AWS IoT Console, the length of client token seems to be limited to 64 bytes.

Below code generating client token does not check the length of client token. So, shadow request sometimes causes errors, when client id and/or shadow name are too long.

https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/shadow/deviceShadow.py#L32-L35

**Comment by rkawajiri** [comment] 2016-12-07 08:57
Below code is my sample of solution. When creating device shadow object, prefix can be set manually.
https://github.com/aws/aws-iot-device-sdk-python/compare/master...strobo-inc:feature/client_token_limits?diff=unified&expand=1&name=feature%2Fclient_token_limits&w=1

**Comment by fengsongAWS** [comment] 2016-12-07 19:22
Thanks @rkawajiri for your interest in AWS IoT SDK. Yes, you are correct. There is no check for the length of client token. Thanks for your effort of pulling request. However, we do not normally directly take PR through github. AWS IoT has its own internal process of releasing but we do give people credit if we take their code into the release. 

Thanks again,
Fengyi

**Comment by rkawajiri** [comment] 2016-12-07 21:21
@fengsongAWS 
Thank you for your reply. I've understood the releasing process.

I have one question. Is there a documentation about the limitation of client token?

**Comment by fengsongAWS** [comment] 2016-12-07 22:19
Unfortunately, there's no documentation about the client token for now which is supposed to be I think. Some SDK e.g. Node.js already dealt with this case while some haven't. You can find more about AWS IoT limit here. [AWS IoT Limit](http://docs.aws.amazon.com/iot/latest/developerguide/iot-limits.html)

**Comment by ftuan** [comment] 2017-05-09 21:20
@fengsongAWS 

Any update on this issue?  I'm getting "ERRORCODE:400 MESSAGE:invalid client token" from AWSIoTLogs in CloudWatch.  I think the error is caused by SDK generating client token longer than 64 bytes.  Is there a way to confirm?  I have the client token from debug logs.

**Comment by liuszeng** [comment] 2017-06-19 21:38
Addressed in [v1.1.2](https://github.com/aws/aws-iot-device-sdk-python/releases/tag/v1.1.2).

**Closed by liuszeng** 2017-06-19 21:38 UTC

**Comment by gbassan-br** [comment] 2019-01-16 22:49
Hi guys!
In fact, this limit is documented here:
https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html#client-token
