### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by soundarsurya** [aws/aws-iot-device-sdk-python#99] opened 2018-01-18 16:49 UTC
when i run the lambda code i get this error....
{
"errorMessage": "Invalid connect options supplied.",
"errorType": "Error",
"stackTrace": [
"Object.Module._extensions..js (module.js:579:10)",
"Module.load (module.js:487:32)",
"tryModuleLoad (module.js:446:12)",
"Function.Module._load (module.js:438:3)"
]
}

where can i able to fix this and how to fix it...????

**Comment by liuszeng** [comment] 2018-01-18 18:27
Closing the issue as it is an exact duplicate of https://github.com/aws/aws-iot-device-sdk-python/issues/98 .

**Closed by liuszeng** 2018-01-18 18:27 UTC
