### ISSUE TITLE
Code getting stuck at myAWSIoTMQTTClient.connect()

### ISSUE THREAD

**Issue by rajibgupta** [aws/aws-iot-device-sdk-python#66] opened 2017-09-17 14:33 UTC
Hi,

An unusual thing happened while using AWS IOT. In my code I try to reconnect to the AWS IOT MQTT server when it fails to upload 5 times continuously.  Below is a snippet of my  code which tries to reconnect.
``` 
                  if resetCounter == 5:
				print "Reset count reached 5...Retry connecting to AWS"
				try:
                                        if myAWSIoTMQTTClient.connect():
						resetCounter = 0;
                       
                                except:
                                        print "Retry failed with some exception"
                                        pass

```

At one moment the code got stuck at the line if myAWSIoTMQTTClient.connect() for around 5-6 hours. I had to restart the code.I have attached the log file below. 
![screenshot 26](https://user-images.githubusercontent.com/3149224/30521845-25ff9a22-9be4-11e7-951d-3a1713a9af28.png)

Any idea why it happened ?

Thanks
Rajib

**Comment by vareddy** [comment] 2017-09-19 23:44
Hi @rajibgupta ,
Thank you for your interest in AWS IoT!
Could you tell us which version of the Python SDK you were using when you encountered this issue? V1.2.0 was released recently so we want to make sure if this is seen in the latest version. 
Also could you try to run the provided sample with the same credentials and see if that works as expected? If it fails, please attach the logs to this issue. 
One more way of testing if the credentials are working is to telnet the IoT endpoint that you are using. 
Please let us know if you have any more questions. 
Thanks!
Varun

**Comment by ashwinpromethean** [comment] 2017-09-20 04:46
Hi Varun, 

I am using python SDK V1.1.2 on a raspberry pi zero. I am not using the latest version since I saw some issues in that version posted here. 

I have mostly integrated the sample code only in my code. I am running it in couple of systems. However as of now the issue is seen in only one system. 

I am running the system 24*7. The issue comes once in 2-3 days. It is very difficult to catch the log with the sample code anytime soon. I will try. 

I think the credentials are fine since it works most of the time. I didn't get the telnet part you mentioned? 

Thanks 
Rajib

**Comment by rajibgupta** [comment] 2017-09-20 08:08
Hi Varun,

I am using python SDK V1.1.2 on a raspberry pi zero. I am not using the latest version since I saw some issues in that version posted here.

I have mostly integrated the sample code only in my code. I am running it in couple of systems. However as of now the issue is seen in only one system.

I am running the system 24*7. The issue comes once in 2-3 days. It is very difficult to catch the log with the sample code anytime soon. I will try.

I think the credentials are fine since it works most of the time. I didn't get the telnet part you mentioned?

Thanks
Rajib

**Comment by vareddy** [comment] 2017-09-22 00:08
HI @rajibgupta,
Could you please running the sample with the same certs as well? This is just to make sure it's not a configuration issue. 
Are there any setup differences between the systems you are running the code on?
Without knowing exactly what your code is doing it is hard to comment on what the issue may be. 
 Thanks!
Varun

**Comment by rajibgupta** [comment] 2017-10-07 17:02
Hi @vareddy 

As of now it is difficult for me to run the sample code since it's installed in a remote location.

I want to clarify again that this happens 1 out of 100 times. 99 times it works fine.

Even if it's a DNS issue, should it get stuck ?

When a connect request times out what is the return ? True or false or something else ?

**Comment by rajibgupta** [comment] 2017-10-23 08:39
@vareddy  Any update ?

**Comment by liuszeng** [comment] 2017-11-27 23:45
Hi @rajibgupta ,

Sorry for having you waited for so long. You can find my answers below:

Ideally, the SDK (v1.1.2) should handle the re-connect for you automatically. The only thing you need to make sure is that you get it pass through the first connect attempt. After the a successful first attempt of connecting, the SDK will be responsible for future reconnects provided any disconnect event.

For connect API call in v1.1.2, it will block the call from returning before it receives a CONNACK back from the server. Based on the configuration you specified for connect and disconnect timeout, it will throw [connectTimeoutException](https://github.com/aws/aws-iot-device-sdk-python/blob/v1.1.2/AWSIoTPythonSDK/exception/AWSIoTExceptions.py#L27). Upon a successful connect, the API will return True.

Hope the above helps.

Thanks,
Liusu

**Comment by liuszeng** [comment] 2017-12-14 22:44
Hi @rajibgupta ,

We have not heard from you for a while. We are closing the issue for now. Please feel free to reopen it or create a new thread if you have any questions.

Thanks,
Liusu

**Closed by liuszeng** 2017-12-14 22:44 UTC

**Comment by rajibgupta** [comment] 2018-03-26 09:44
Hi @liuszeng,

I removed the line for manually connecting to AWS. Now the code doesn't get stuck. 

But the problem is sometimes even if stable Internet connection is available, it stops automatically reconnecting. It stays disconnected until I reboot the Rpi. 
How to tackle this?
