### ISSUE TITLE
Unsubscribe in Subscription Callback?

### ISSUE THREAD

**Issue by Archetype90** [aws/aws-iot-device-sdk-python#78] opened 2017-10-16 17:17 UTC
Is it possible to unsubscribe from a topic in the subscription callback? When I do that logic, and attempt to unsubscribe after a message has been received on a topic, I get this error after the first successful receipt of data:

`AWSIoTPythonSDK.exception.AWSIoTExceptions.unsubscribeTimeoutException`

So I publish to an MQTT topic with a callback, receive data, and unsubscribe from the topic in the callback. But, when publishing to the same topic and callback, it gets the error above. Everything works fine every time if I follow:

1. Subscribe with callback
2. Callback executes business logic
3. Unsubscribe from topic

But that results in a lot of "unsubscribe" code duplication when it could just be put in the subscription callback.

**Comment by hedeshianaws** [comment] 2017-10-16 17:33
@Archetype90 Thank you for your interest in AWS IoT. This actually looks like a duplicate of #77. I'm going to close this issue for now, please continue to track in #77. Feel free to re-open this ticket if you have additional questions, or if you think this has been closed in error.

**Closed by hedeshianaws** 2017-10-16 17:33 UTC
