### ISSUE TITLE
Frequent [Errno 104] Connection reset by peer message

### ISSUE THREAD

**Issue by cspinillo** [aws/aws-iot-device-sdk-python#109] opened 2018-02-08 18:58 UTC
I am having a continual connectivity issue that I've never run into before and am unsure of how to diagnose.

I'm getting: [Errno 104] Connection reset by peer frequently, sometimes hindering any sort of interaction on it.

My Code is as follows:

```
# For certificate based connection
myShadowClient = AWSIoTMQTTShadowClient("SmartAisle_Production")
myShadowClient.configureEndpoint("a1oia27wb760k3.iot.us-east-1.amazonaws.com", 8883)
myShadowClient.configureCredentials("keys/root-CA.pem", "keys/9ae8062dc8-private.pem.key", "keys/9ae8062dc8-certificate.pem.crt")
myShadowClient.configureConnectDisconnectTimeout(17)  # 10 sec
myShadowClient.configureMQTTOperationTimeout(12)  # 5 sec
myShadowClient.connect()

# # Shadow Details
myDeviceShadow = myShadowClient.createShadowHandlerWithName("SmartAisle_Production", True)
myDeviceShadow.shadowGet(initOnCallBack, 5)
myDeviceShadow.shadowRegisterDeltaCallback(shadowCallBack)
```

I'v e tried websocket connection, and it's basically the same issues. It's really blocking a lot of interactions at this point and can't seem to figure it out. Logs largely look fine:

I see the following error occasionally:

```
{
    "timestamp": "2018-02-06 01:37:35.259",
    "logLevel": "ERROR",
    "traceId": "1147acac-045c-c8d7-4f14-a223fb48a275",
    "accountId": "640017232091",
    "status": "Failure",
    "eventType": "Connect",
    "protocol": "MQTT",
    "clientId": "SmartAisle_Production",
    "principalId": "9ae8062dc8b86495604df5f76d7bf925481ece8d33fd1cc0de836a4dec546303",
    "sourceIp": "172.58.224.34",
    "sourcePort": 29000,
    "reason": "throttled"
}
```

Any thoughts, ideas or solutions are welcome.

**Comment by liuszeng** [comment] 2018-02-09 00:49
Hi @cspinillo ,

From the log you provided, it seems that your MQTT connection is being throttled. You may want to check if your publisher and subscriber are exceeding any existing limit of AWS IoT:
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot

Thanks,
Liusu

**Comment by cspinillo** [comment] 2018-02-12 18:43
Hi @liuszeng ,

I have a single lambda instance that's driving an alexa skill. It's thresholds are elevated to allow for higher traffic use, but nothing crazy, either. I'm totally unsure of how to diagnose this problem as there are 0 error logs, my file size is well within the spec and I can see the connections firing successfully on both ends.

Any ideas on how to debug or trouble shoot the issue would be awesome.

Christian

Note: My above code executes outside of the while loop, so it's not being called repeatedly either

**Comment by liuszeng** [comment] 2018-02-12 19:15
Hi @cspinillo ,

Can you specify more about how you get the "throttling log"? AWS Lambda and AWS IoT are different services that have different throttling limits. If the log is coming from AWS IoT CloudWatch logs, most likely you are throttled by AWS IoT, even your lambda configuration allows a higher traffic use. Also, AWS IoT throttling counts both inbound and outbound traffic, which means you will get throttled even if you are only receiving messages and there are too many of them.

Thanks,
Liusu

**Comment by cspinillo** [comment] 2018-02-12 19:53
@liuszeng 

Those logs are in my AWS IoT logs, but the message I'm getting in my python output is:

[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer
[Errno 104] Connection reset by peer

These are what i'm trying to troubleshoot but finding 0 cause at this point.

Christian

thanks for all your help

**Comment by liuszeng** [comment] 2018-02-12 21:40
Hi @cspinillo ,

Are the following logs coming from your AWS IoT CloudWatch Logs?

```
{
    "timestamp": "2018-02-06 01:37:35.259",
    "logLevel": "ERROR",
    "traceId": "1147acac-045c-c8d7-4f14-a223fb48a275",
    "accountId": "640017232091",
    "status": "Failure",
    "eventType": "Connect",
    "protocol": "MQTT",
    "clientId": "SmartAisle_Production",
    "principalId": "9ae8062dc8b86495604df5f76d7bf925481ece8d33fd1cc0de836a4dec546303",
    "sourceIp": "172.58.224.34",
    "sourcePort": 29000,
    "reason": "throttled"
}

Thanks,
Liusu
```

**Comment by cspinillo** [comment] 2018-02-12 21:41
@liuszeng  Yes. They are.

**Comment by liuszeng** [comment] 2018-02-12 22:10
Hi @cspinillo ,

You are getting throttled by AWS IoT. You can think of the AWS IoT CloudWatch logs as the server logs. Due to MQTT specifications, client is not able to extract more information about the root cause when issue happens.

You may want to check the following things to make sure they are within the AWS IoT throttling limits:
1. Number of PUBLISH per second per client connection. Note that this means publishes from another client and from AWS IoT server.
2. Data throughput per second. This is closely related to how big your inbound/outbound payload is and how fast they are sent.

Also, where does the Python SDK code live, in a stand-alone application or in your lambda function?

Thanks,
Liusu

**Comment by cspinillo** [comment] 2018-02-13 16:16
The python SDK resides on a raspberry Pi that is communicating with a NodeJS lambda function.

**Comment by cspinillo** [comment] 2018-02-13 16:49
Ok, update. 

So, I updated a few portions of my code:

```
myShadowClient.configureAutoReconnectBackoffTime(1,32,20)
```

And then in my call backs I removed: 
```
myDeviceShadow.shadowGet(initOnCallBack, 5)
```
and now just have:

```
myDeviceShadow = myShadowClient.createShadowHandlerWithName("Thing", True)
myDeviceShadow.shadowRegisterDeltaCallback(shadowCallBack)
```

**Comment by liuszeng** [comment] 2018-02-13 18:03
Hi @cspinillo ,

There are many reasons a client can get throttled. I have the following questions:
1. What is the data flow in your system? In other words, how is the message being passed around through different components of your system?
2. Is the Raspberry Pi only listening on shadow delta messages? Does it do any other shadow operations, e.g., shadow get/update in its delta callback?
3. Is the lambda function performing any shadow operations? How frequent is it being invoked?

Thanks,
Liusu

**Comment by cspinillo** [comment] 2018-02-13 19:08
Ok, so here is order of procedure.

1. We have a raspberry pi that has a small, stand alone application on it. The important code is:

```
def shadowCallBack(payload,status,token):
    payloadObj = json.loads(payload)
    modeManager(payloadObj["state"]["mode"],payloadObj["state"]["lights"])

# For certificate based connection
myShadowClient = AWSIoTMQTTShadowClient("SAP")
myShadowClient.configureEndpoint("xxxx.iot.us-east-1.amazonaws.com", 8883)
myShadowClient.configureCredentials("keys/root-CA.pem", "keys/private.pem.key", "keys/certificate.pem.crt")
myShadowClient.configureAutoReconnectBackoffTime(1,32,20)
myShadowClient.configureConnectDisconnectTimeout(10)  # 10 sec
myShadowClient.configureMQTTOperationTimeout(5)  # 5 sec

# # Shadow Details
myShadowClient.connect();
myDeviceShadow = myShadowClient.createShadowHandlerWithName("ThingName", True)
myDeviceShadow.shadowRegisterDeltaCallback(shadowCallBack)
# END IOT

# Loop forever
while True:
    ledBreathe()
    time.sleep(1.0 /70)
```

On the lambda application, which is simply a NodeJS app for an Alexa skill, we have the following:

```
const IOT_Thing = process.env.IOT_THING_NAME;
const Alexa = require('alexa-sdk');
const AWS = require('aws-sdk');
AWS.config.region = process.env.IOT_REGION;
const IOT_Data = new AWS.IotData({endpoint: process.env.IOT_ENDPOINT});
```

Then, in code: 
```
function shadowUpdate(dataObj,mode){
  if(process.env.ENVIRONMENT === "PROD"){
    var lightObj={"state":
        {
        "desired":{
        "lights":dataObj,"mode":mode
        }
      }
    };
    var payloadObj = {"thingName": IOT_Thing,"payload":JSON.stringify(lightObj)}
    IOT_Data.updateThingShadow(payloadObj, function (err, data) {
      if (err) console.log(err, err.stack); // an error occurred
      else     console.log("IOT DATA: "+JSON.stringify(data));   
    })
  }
}
```

The shadowUpdate is called periodically through out the Alexa interaction, but it's not firing more than intended, as I don't see any debug logs in my cloudwatch for the lambda. 

The approximate number of shadow updates per skill interaction is 3 - 5. The average engagement experience is 35 - 45 seconds.

**Comment by liuszeng** [comment] 2018-02-13 20:31
Hi @cspinillo ,

Thank you very much for providing the detailed information.

From your description, it seems that the only place the Python SDK client is having traffic from is the shadow update in the lambda function, which is triggered by Alexa interactions. I would encourage you to check the TPS (Transaction Per Second) and the message payload size of these shadow operations and see if any of them are in violation of any existing AWS IoT limits.

One minor thing I noticed is that, the CloudWatch log you attached earlier shows the client being throttled has a client id set to `SmartAisle_Production`, while your python code has the client id configured as `SAP`. I am assuming it is the log from shadow operations in the lambda function. Can you confirm?

As the support is kinda deviating towards an overall system/solution evaluation instead of pure SDK issues, I would also encourage you to open up a thread on our AWS Forums or reach out to AWS support to get a more professional and focused support.

Thanks,
Liusu

**Comment by cspinillo** [comment] 2018-02-13 21:41
Yeah, I removed the references for purpose of github discussion.

SmartAisle_Production is actually the "thing" name.

I've posted at AWS IoT forums to no avail. Will keep trying and testing.

The invocations are so minor that I can't see that being the cause. More research is necessary I suppose.

**Comment by liuszeng** [comment] 2018-02-14 17:11
Closing as the issue is not directly related to SDK. Forwarded the feedback to internal teams for more informative cloud watch logs for root cause of throttling.

**Closed by liuszeng** 2018-02-14 17:11 UTC
